
# Generated by /Users/soegaard/BuildRacketLibs/cmake/bootstrap
# Default cmake settings.  These may be overridden any settings below.
set (CMAKE_INSTALL_PREFIX "/Users/soegaard/BuildRacketLibs" CACHE PATH "Install path prefix, prepended onto install directories." FORCE)
set (CMAKE_DOC_DIR "doc/cmake-2.8" CACHE PATH "Install location for documentation (relative to prefix)." FORCE)
set (CMAKE_MAN_DIR "man" CACHE PATH "Install location for man pages (relative to prefix)." FORCE)
set (CMAKE_DATA_DIR "share/cmake-2.8" CACHE PATH "Install location for data (relative to prefix)." FORCE)

